# -*- coding: utf-8 -*-
"""Brute-force.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W-Fxz5Uzj2Nzev5DP3-eCsG-Im2UWWEX

# Auto-generate array function
"""

from numpy.random import seed
from numpy.random import randint

def auto_gen():
  # Using numpy libraryto auto-generate an array of integers 
  # Output: auto-generate an array of integers 
  array = randint(0,100,randint(1,10))

  return array

#Implementation
print(auto_gen())

"""# Selection sort algorithm"""

def sele_sort(A):
  #Sorts a given array by selection sort
  #Input: An array A[0..n − 1] of orderable elements
  #Output: Array A[0..n − 1] sorted in nondecreasing order

  # Get A length
  n = len(A)
  for i in range(0,n):
    min = i
    for j in range(i+1,n):
      if A[j] < A[min]:
        min = j
    A[i],A[min] = A[min],A[i]
  return A

#Implementation
A = auto_gen()
print(sele_sort(A))

"""## Note:

* Pseudo code in refereneced book is basically false in identifying the end point for the both loop if we are progrmming in Python
* Remember that, in Python `range` always has its end point at `n-1`

# Run-time and run-time graph
"""

import time 
import pylab 
import random

def time_sele_sort():
  input_size = []
  timer = []

  for i in range(2,100):
    input_size.append(i)
    temp = []
    for j in range(i):
      temp.append(random.randint(0,10))
    start = time.time()
    sele_sort(temp)
    end = time.time()

    timer.append((end-start) * 1000)
  
  pylab.plot(input_size,timer, 'o-')
  pylab.show()

#Implementation
time_sele_sort()

